### ISSUE TITLE
MIA FDA Volume 1 Technical Proposal Checklist

### ISSUE THREAD

**Issue by HadleyKing** [UCI-ICTS/mia#20]
## Fifty [50] page limit for items 4 to 11)

see page 103 [here](https://www.fda.gov/media/173088/download?attachment)
- [ ] 1. Cover page
- [ ] 2. Official Transmittal Letter
- [ ]  3. Table of contents
- [ ]  4. Executive Summary
- [ ]  5. Research and Development Justification
- [ ]  6. Scientific and Technical Information
- [ ]  7. Regulatory Science Impact
- [ ]  8. Resources Proposed
- [ ]  9. Gantt Chart, Work Breakdown Structure and Milestones
- [ ]  10. Deliverable Schedule
- [ ]  11. Risk mitigation plan
- [ ]  12. Security Planning
- [ ]  13. Intellectual Property
- [ ]  14. Bibliography/References
- [ ]  Appendix
  - [ ] Biographic sketches (required)
  - [ ]  Intellectual Property (required)
  - [ ] Statement of Work (required)
  - [ ] Protection of Human Subjects (if applicable)
  - [ ] Animal Use (if applicable)
  - [ ] Use of Select Agents (if applicable)
  - [ ] Laboratory License Requirement (if applicable)
  - [ ] Security (if applicable)
  - [ ] Good Laboratory Practice (GLP) Compliance (if applicable)
  - [ ] Good Manufacturing Practices (GMP) Compliance (if applicable)
  - [ ] Good Clinical Practice (GCP) Compliance (if applicable)
